#!/usr/bin/env bash
# Guardrails that must survive wording/refactor changes.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
check() {
  local file="$1" pattern="$2"
  rg -q --fixed-strings "$pattern" "$ROOT/$file" || {
    echo "missing guardrail: $file :: $pattern" >&2
    exit 1
  }
}

check claude/agents/SCC-v1.0.1.md "Validation Package"
check claude/agents/SCC-v1.0.1.md "ข้อความคำขอและ scope ที่ผู้ใช้อนุมัติ"
check claude/agents/SCC-v1.0.1.md "comment ตั้งแต่ 2 บรรทัดขึ้นไป"
check claude/agents/SCC-v1.0.1.md "ห้ามวนอ่านโค้ดเพื่อเดาข้อจำกัดภายนอก"
check claude/agents/SCC-v1.0.1.md "แยกคำถาม/ข้อสังเกตออกจากคำสั่งให้ดำเนินการ"
check claude/agents/SCC-v1.0.1.md "ลอง alternative ที่สมเหตุสมผลหนึ่งทาง"
check claude/agents/SCC-v1.0.1.md "สร้าง task list **ก่อน mutation**"
check claude/agents/SCC-v1.0.1.md "ห้าม big-bang rewrite"
check claude/agents/SCC-v1.0.1.md "นี่ไม่ใช่ authorization"
check claude/agents/SCC-v1.0.1.md "Behavioral Gates (trigger → action)"
check claude/agents/SCC-v1.0.1.md "claim → สิ่งที่ต้องสังเกต → วิธีตรวจ → ผลที่ได้"
check claude/agents/SCC-v1.0.1.md "ห้ามขยายผล “ไม่พบ” เกิน query"
check claude/agents/SCC-v1.0.1.md "การพบ artifact อย่างเดียวไม่พิสูจน์ว่า active"
check claude/agents/SCC-v1.0.1.md "ก่อนรายงานผล, finding หรือ handoff"
check claude/agents/SCC-v1.0.1.md "ห้ามรายงานสิ่งที่ได้รับมาหรือผลค้างเหมือนตรวจเอง"
check claude/agents/SCC-v1.0.1.md "ตรวจ primary evidence โดยตรงให้ครบทุก atomic finding ที่จะเขียน"
check claude/agents/SCC-v1.0.1.md "inventory entry point/consumer/contract/test"
check claude/agents/SCC-v1.0.1.md "migrate และตรวจ consumer ก่อนลบของเดิม"
check claude/agents/SCC-v1.0.1.md "ปิดงานทุกครั้งด้วยบรรทัดนี้"
check claude/agents/SCC-v1.0.1.md "เข้าใจ → ค้นคว้า → ออกแบบ → ลงมือ → ตรวจสอบ → บันทึกสิ่งที่โค้ดเล่าเองไม่ได้"
check claude/agents/SCC-v1.0.1.md 'invoke `greenfield-foundation` ก่อนเสนอ stack หรือ mutation'
check claude/agents/SCC-v1.0.1.md "official LTS/support lifecycle, EOL และ compatibility ของ version chain ปัจจุบัน"
check claude/agents/ACV-v1.0.1.md "behavior ของ ACV"
check claude/agents/ACV-v1.0.1.md "Requirement, observable evidence และข้อจำกัดให้เป็น Finding/Verdict"
check CLAUDE.md "Design invariant — สามชั้นมีหน้าที่ต่างกัน"
check CLAUDE.md '`agents/` = behavior ของผู้ปฏิบัติงาน'
check CLAUDE.md '`rules/` = กฎกลางร่วมและ safety invariant'
check CLAUDE.md '`skills/` = มาตรฐานและ procedure เฉพาะงาน'
check CLAUDE.md "invariant → trigger/action → domain procedure"
check claude/rules/core/operating-contract.md "Pain ที่ตรวจพบห้ามเงียบ"
check claude/rules/core/operating-contract.md "domain detail ที่ลึกอยู่ใน skill แบบ on-demand"
check claude/rules/core/operating-contract.md "skill ห้ามลด safety floor ของ rules"
check claude/rules/core/operating-contract.md "Research escalation"
check claude/rules/core/operating-contract.md "Greenfield foundation gate"
check claude/rules/core/operating-contract.md "official LTS/support lifecycle"
check claude/rules/core/operating-contract.md "ทุก greenfield"
check claude/rules/core/evidence-integrity.md "Workspace-evidence gate"
check claude/rules/core/evidence-integrity.md "ยังไม่พบใน repo"
check claude/rules/core/evidence-integrity.md "Evidence-integrity gate"
check claude/rules/core/evidence-integrity.md "ผล “ไม่พบ” พิสูจน์ได้เพียงว่า query นั้น"
check claude/rules/core/evidence-integrity.md "ผลที่ได้รับไม่ใช่ข้อพิสูจน์โดยอัตโนมัติ"
check claude/rules/core/evidence-integrity.md "Report-integrity gate"
check claude/rules/core/evidence-integrity.md "ผลค้างหรือคำบอกต่อห้ามรายงานเหมือนผู้รายงานได้รันเอง"
check claude/rules/core/evidence-integrity.md "Durable-finding gate"
check claude/rules/core/evidence-integrity.md "provenance ที่ตรวจย้อนกลับได้"
check claude/rules/core/evidence-integrity.md "Failure-escalation gate"
check claude/rules/core/change-control.md "Refactor gate"
check claude/rules/core/change-control.md "behavior-preserving/internal change"
check claude/rules/core/change-control.md "Intent gate"
check claude/rules/core/change-control.md "Execution-tracking gate"
check claude/rules/core/change-control.md "ก่อน mutation"
check claude/agents/ACV-v1.0.1.md 'ไม่มีหลักฐานที่ยืนยัน Acceptance Criterion ไม่ใช่ `PASS`'
check claude/agents/ACV-v1.0.1.md "ทุก Finding ต้องมี"
check claude/agents/ACV-v1.0.1.md "Verification ที่จำเป็นล้มเหลว, ถูก skip หรือรันไม่ได้"
check claude/agents/ACV-v1.0.1.md "ห้ามถือว่าการทำงานได้เท่ากับผู้ใช้อนุมัติให้ทำ"
check claude/agents/ACV-v1.0.1.md "อย่างใดอย่างหนึ่งแทนกันไม่ได้"
check claude/agents/ACV-v1.0.1.md "ตรวจการจำแนก behavioral change"
check claude/agents/ACV-v1.0.1.md "ไม่ใช่ตัดสินแทนผู้ใช้ว่าควรเลือกทางใด"
check claude/agents/ACV-v1.0.1.md "ห้ามใช้ absence จาก probe เดียวเป็น Verdict"
check claude/agents/ACV-v1.0.1.md "ใช้ยืนยันสถานะปัจจุบันไม่ได้"
check claude/agents/ACV-v1.0.1.md "Report, summary, transcript หรือผลที่ได้รับเป็นข้อมูลนำเข้า"
check claude/agents/ACV-v1.0.1.md "งาน greenfield เลือก runtime/framework/database/toolchain/SDK/platform หรือ version"
check claude/agents/ACV-v1.0.1.md "clean install/build/runtime evidence"
check claude/rules/engineering/documentation-discipline.md "ตั้งแต่ 2 บรรทัด"
check claude/rules/engineering/documentation-discipline.md "status (Verified/Unverified/Contradicted)"
check claude/rules/engineering/compatibility-rollout.md "Expand → Migrate → Contract"
check claude/rules/risk/production-recovery.md "health signal มาจาก **สถานะ**"
check claude/rules/risk/production-recovery.md "restore ต้องเคยซ้อมจริง"
check claude/rules/risk/external-integration-safety.md "เก็บ raw event ก่อนประมวลผล"
check claude/skills/api-design/SKILL.md 'inventory `list/get/create/update/delete`'
check claude/skills/api-design/SKILL.md "inventory เป็นการวิเคราะห์ ไม่ใช่ authorization"
check claude/skills/greenfield-foundation/SKILL.md "LTS & Compatibility Gate — บังคับทุก greenfield"
check claude/skills/greenfield-foundation/SKILL.md "ห้ามใช้ความจำของ model ยืนยัน “current LTS”"
check claude/skills/greenfield-foundation/SKILL.md "clean install/build/runtime"
if find "$ROOT/claude/rules" -maxdepth 1 -type f -name '*.md' | rg -q .; then
  echo "rules must be owned by core/, engineering/, or risk/" >&2
  exit 1
fi
check claude/skills/docs/placement/SKILL.md "ตั้งแต่ 2 บรรทัดขึ้นไป"
check claude/skills/docs/setup/kit/hooks/docs-drift.sh "New multi-line line-comment(s)"
if rg -q 'docs:placement|docs-setup|/docs:' "$ROOT/claude/skills/docs/setup/kit/hooks/docs-drift.sh"; then
  echo "hook must not reference an optional skill" >&2
  exit 1
fi
check claude/skills/api-design/SKILL.md "api-design:contract-core"
check claude/skills/api-design/contract-core/SKILL.md "OpenAPI หรือ JSON Schema"
check claude/skills/api-design/errors/SKILL.md "Problem Details"
check claude/skills/api-design/collections/SKILL.md "tie-breaker ที่ stable"
check claude/skills/api-design/mutations/SKILL.md "Idempotency-Key"
check claude/skills/api-design/async-operations/SKILL.md "202 Accepted"
check claude/skills/api-design/caching-concurrency/SKILL.md "If-Match"
check claude/skills/api-design/evolution/SKILL.md "behavioral-change gate"
check claude/skills/data-design/SKILL.md "data-design:lifecycle-governance"
check claude/skills/data-design/SKILL.md "ใช้ทันทีเมื่อวางแผน, ออกแบบ, review"
check claude/skills/data-design/SKILL.md "แม้ยังไม่มี schema/repo จริงหรือผู้ใช้ขอเพียงแผน"
check claude/skills/data-design/caching/SKILL.md "ห้ามใส่ cache จนกว่าจะตอบครบ 3 ข้อ"
check claude/skills/data-design/transactions-invariants/SKILL.md "transactional outbox"
check claude/skills/data-design/lifecycle-governance/SKILL.md "soft delete ไม่ใช่ privacy erasure"
check claude/skills/ui-ux-baseline/SKILL.md "interactive element ทุกชนิด"
check claude/skills/ui-ux-baseline/SKILL.md "ใช้ทันทีเมื่อวางแผน, ออกแบบ, review"
check claude/skills/ui-ux-baseline/SKILL.md "แม้ยังไม่มีไฟล์จริงหรือผู้ใช้ขอเพียงแผน"
check claude/skills/ui-ux-baseline/SKILL.md "ui-ux-baseline:visual-direction"
check claude/skills/ui-ux-baseline/SKILL.md "ui-ux-baseline:motion-microinteractions"
check claude/skills/ui-ux-baseline/SKILL.md "ui-ux-baseline:design-foundations"
check claude/skills/ui-ux-baseline/SKILL.md "ui-ux-baseline:content-localization"
check claude/skills/ui-ux-baseline/SKILL.md "decorative emoji ใน UI"
check claude/skills/ui-ux-baseline/resource-states/SKILL.md "เกิดได้จริงจาก data flow"
check claude/skills/ui-ux-baseline/realtime-conversation/SKILL.md "scroll ขึ้น = ปลด sticky"
check claude/skills/ui-ux-baseline/interaction-a11y/SKILL.md "focus-visible"
check claude/skills/ui-ux-baseline/interaction-a11y/SKILL.md "prefers-reduced-motion"
check claude/skills/ui-ux-baseline/visual-direction/SKILL.md "aesthetic thesis"
check claude/skills/ui-ux-baseline/visual-polish/SKILL.md "shadow, blur, gradient, overlay"
check claude/skills/ui-ux-baseline/motion-microinteractions/SKILL.md "prefers-reduced-motion"
check claude/skills/ui-ux-baseline/design-foundations/SKILL.md "semantic color/contrast"
check claude/skills/ui-ux-baseline/design-foundations/SKILL.md "ห้ามใช้ emoji ตกแต่ง UI โดย default"
check claude/skills/ui-ux-baseline/design-foundations/SKILL.md "ให้เสนอ icon ที่มี semantic ตรงจาก library เดิมแทน"
check claude/skills/ui-ux-baseline/design-foundations/SKILL.md "Refactor Icon & Emoji"
check claude/skills/ui-ux-baseline/content-localization/SKILL.md "ห้ามสร้างระบบ i18n ขนาน"
check claude/skills/ui-ux-baseline/content-localization/SKILL.md "Extract โดยคง behavior"
check claude/skills/ui-ux-baseline/feedback-notifications/SKILL.md "อย่าเริ่มด้วย Toast เพราะทำง่าย"
check claude/skills/ui-ux-baseline/feedback-notifications/SKILL.md "partial failure ห้ามสรุปว่า “สำเร็จ”"
check claude/skills/ops/infra-change/SKILL.md "ก่อน apply อธิบาย target, plan, risk, rollback/mitigation และขอ authorization"
check claude/skills/ops/incident-response/SKILL.md "owner authorization ก่อนทำ"
check claude/skills/ops/observability/SKILL.md "event log เงียบอย่างเดียวไม่ใช่ health signal"
check claude/skills/docs/setup/kit/CLAUDE.template.md 'เป็น **link**'
check claude/skills/docs/setup/kit/CLAUDE.template.md "Research escalation — เริ่มที่ repo แต่ห้ามจมอยู่ใน repo"
check claude/skills/docs/setup/kit/CLAUDE.template.md "## Execution tracking"
check claude/skills/docs/setup/kit/CLAUDE.template.md "## Report integrity"
check claude/skills/docs/setup/kit/CLAUDE.template.md "## Durable findings"

echo "guardrails verified"
